### ISSUE TITLE
show RSS link on search page when no term is provided

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic#102]
The RSS link only shows up on the search page when you've entered a search term:

<img width="1252" alt="screen shot 2016-11-16 at 4 23 09 pm" src="https://cloud.githubusercontent.com/assets/919583/20368350/4197231a-ac19-11e6-9435-e2da75772bef.png">

For those that want to subscribe to tags/filters like 'Zoning reclassification', there is link shown. Let's add it!

Related to https://github.com/datamade/chi-councilmatic/issues/154

**Comment by reginafcompton** [comment]
This is done.

<img width="1245" alt="screen shot 2016-11-30 at 4 45 05 pm" src="https://cloud.githubusercontent.com/assets/13078679/20774551/708e806a-b71c-11e6-9ff9-cbcf6b6053f8.png">
