### ISSUE TITLE
add some kind of date control to search

### ISSUE THREAD

**Issue by cathydeng** [datamade/django-councilmatic#11]
legislative session? year? more granular?

**Comment by fgregg** [comment]
I think the default should be the current legislative session. And then
maybe toggle that with everything?

On Thu, Dec 10, 2015 at 10:04 AM, Cathy Deng <notifications@github.com>
wrote:

> legislative session? year? more granular?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/django-councilmatic/issues/11>.
>



-- 
773.888.2718
