### ISSUE TITLE
Tags for versioned releases

### ISSUE THREAD

**Issue by notpeter** [datamade/django-councilmatic#129]
Hey folks,

Can you please tag in git when a [pypi packaged versions](https://pypi.python.org/pypi/django-councilmatic) goes out?

Thanks
-Peter

**Comment by fgregg** [comment]
what does this enable for you?

**Comment by notpeter** [comment]
It enables easy viewing code for a particular pypi release and the ability what's changes between  release. 

As it stands currently, the git repo can't do any of these:
1. What code is in that 0.7.6
2. Diff between 0.7.6..master
3. If I pip install `django-councilmatic<0.7` (e.g. [datamade/councilmatic-starter-template](https://github.com/datamade/councilmatic-starter-template) requirements.txt) what version am I getting? Oh there was a 0.6.9 release back in October...What's changed since then?
etc

If you're releasing versioned packages on pypi, your Git repo should have matching metadata.

P.S. I know I can download tarballs for each release from pypi, but I just want to be able to go `git checkout v0.7.6` and have source code matching a past/current release.

**Comment by fgregg** [comment]
thanks for your explanation. this is probably not a step we are going to add to our process. we may change our deployment to happen automatically on tagged commits, which would produce what you want
