### ISSUE TITLE
wire up geocoding on council member map

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic#16]
People should be able to look up their alderman based on their address. I believe we already have everything we need for doing this with OCD, right @evz?

**Comment by evz** [comment]
Yup. OCD will give us point in polygon lookups. We just need the point.

**Comment by derekeder** [comment]
Rad - I can hook that part up.

On Thu, Dec 31, 2015 at 1:34 PM, Eric van Zanten <notifications@github.com>
wrote:

> Yup. OCD will give us point in polygon lookups. We just need the point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/django-councilmatic/issues/16#issuecomment-168237718>
> .
>



-- 
Derek Eder
@derekeder <https://twitter.com/#%21/derekeder>
derek@derekeder.com
derekeder.com

**Comment by derekeder** [comment]
Working branch here https://github.com/datamade/django-councilmatic/tree/district-lookup

**Comment by derekeder** [comment]
closed via #24
