### ISSUE TITLE
Is SEO harmed by having content for a bill spread over four pages?

### ISSUE THREAD

**Issue by fgregg** [datamade/django-councilmatic#20]
For this bill, for example. 

The history, sponsors, full text, attachments, and comments are spread over 5 distinct urls.

http://nyc.councilmatic.org/legislation/int-908-2015/

If I was google, I would have hard time knowing which was the canonical page for that information. I think we should load all the content at once, and do the tabbing in javascript?

Thoughts @derekeder @cathydeng

**Comment by derekeder** [comment]
I was thinking along the same lines for Chicago from a UI perspective. You have to click a lot to see all things associated with a bill.

I propose we change it from links to a sectioned list.
