### ISSUE TITLE
Use 'Meetings' instead of 'Events'?

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic#23]
I know we settled on 'Events' a while back, but 'Meetings' sounds more accurate. Is there any reason to keep using 'Events' ?

**Comment by fgregg** [comment]
IN New York, there are things like tours which are not meetings. In chicago I think we just have meetings

**Comment by derekeder** [comment]
I think @cathydeng is stripping out tours from the display in NY. Is that correct?

**Comment by fgregg** [comment]
We are not stripping them out from the events page,

**Comment by derekeder** [comment]
Hmm ok. I think I'd still rather use a word that makes sense for the things we care about (the committee and council meetings) than tailor it to this exception.

Unless there's a strong objection, I'm going to make the change.

**Comment by cathydeng** [comment]
this sounds like one of the things we should set in city specific settings - was going to add vocab settings for things like 'aldermen' vs 'council members'

**Comment by derekeder** [comment]
Good point. Lets do that.

**Comment by derekeder** [comment]
Resolved by @cathydeng in https://github.com/datamade/django-councilmatic/commit/e67ffbc60b36057f9a087a7d65024d63ceef4f25
