### ISSUE TITLE
import_data: Consider adding a mechanism for removing stale bill subjects

### ISSUE THREAD

**Issue by reginafcompton** [datamade/django-councilmatic#236]
The subjects of a bill can change, including when a bill loses a subject once related to that bill.

This recently caused an issue in Metro Councilmatic. [Private bills (previously) had a subject "Restricted View,"](https://github.com/opencivicdata/scrapers-us-municipal/pull/266) but when those private bills were toggled to public the subject persisted in the Councilmatic database. 

It seems reasonable to delete all subjects of updated bills, before adding new ones. [We implemented this pattern with EventAgendaItems.](https://github.com/datamade/django-councilmatic/blob/8d64575cf93470d13db99db9f4d42afd3a67cc5c/councilmatic_core/management/commands/import_data.py#L3209) Presumably, many bills in the Councilmatic universe have stale subjects, which should be removed.

**Comment by hancush** [comment]
Pre-requisite for https://github.com/datamade/la-metro-councilmatic/issues/432.
