### ISSUE TITLE
Create management command for importing shapefiles

### ISSUE THREAD

**Issue by jeancochrane** [datamade/django-councilmatic#248]
Pull out logic from the soon-to-be deprecated `import_data` command into its own management command, `import_geographies`. Specifically, adapt this method, making sure it fits with the new models introduced in #240:

https://github.com/datamade/django-councilmatic/blob/5387ae85ea289b22c4e0ea566fa89a1c43155ed0/councilmatic_core/management/commands/import_data.py#L3196-L3226

**Comment by fgregg** [comment]
I'd like to see if we can lean into the collect static approach. If that's not desirable for some reason, please let me know.

https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/

**Comment by jeancochrane** [comment]
Closed in #249.
