### ISSUE TITLE
For SEO, combine the councilmember's profile view to single page

### ISSUE THREAD

**Issue by fgregg** [datamade/django-councilmatic#25]
Combine http://chicouncilmatic.datamade.us/person/hairston-leslie-a/?view=committees and http://chicouncilmatic.datamade.us/person/hairston-leslie-a/?view=bills to single page and do tabbing with javascript.

**Comment by reginafcompton** [comment]
<img width="630" alt="screen shot 2017-02-23 at 10 52 44 am" src="https://cloud.githubusercontent.com/assets/13078679/23269454/3e0054ac-f9b6-11e6-9e9f-d2095b4f7e8a.png">
