### ISSUE TITLE
bad form validation when editing a persin in the admin

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic#255]
In trying to update Mayor Lightfoot's photo, getting a page validation error that I'm not sure how to get past on the person edit page: https://chicago.councilmatic.org/admin/core/person/ocd-person_2Fcb902e98-e70c-41bb-8995-f6faf37c9643/change/

<img width="1279" alt="Screen Shot 2019-08-08 at 11 21 28 AM" src="https://user-images.githubusercontent.com/919583/62720000-bd30bc00-b9ce-11e9-8c63-875c2f39bd4e.png">

**Comment by fgregg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Django-Councilmatic Django-Admin bug](https://trello.com/c/NF3elrYS/2-django-councilmatic-django-admin-bug)

**Comment by fgregg** [comment]
this is fixed now @derekeder, you can update the images of folks at your leisure

**Comment by fgregg** [comment]
this what fixed it https://github.com/opencivicdata/python-opencivicdata/pull/122
