### ISSUE TITLE
better loaddata logging

### ISSUE THREAD

**Issue by cathydeng** [datamade/django-councilmatic#33]
we should print a count of how many things were updated & how many things were added, for each type of object.

also would be nice to have a count of how many things we have to look through on the ocd api (https://github.com/datamade/chi-councilmatic/issues/118) to estimate progress, since loaddata takes a long time. @fgregg can we get counts from the api?

also we should revisit this issue after i put together guidelines for logging

**Comment by fgregg** [comment]
yup, every query response should have a "meta" object with the count of the
number of objects returned

.
datamade.us/bills/?from_organization=ocd-organization/ef168607-9135-4177-ad8e-c1f7a4806c3a&title__icontains=settlement

**Comment by cathydeng** [comment]
oh right, we use that for the page count. cool.

**Comment by reginafcompton** [comment]
Eric did this! With loads of ASCII art, too.
