### ISSUE TITLE
add some docs for re-deploying councilmatic

### ISSUE THREAD

**Issue by cathydeng** [datamade/django-councilmatic#34]
high level overview, steps to get started, & recommendations. make sure to link from chi-councilmatic & nyc-councilmatic

thx to @patcon & @wordyallen we can make this less painful for peeps in the future

**Comment by fgregg** [comment]
This should be happening in https://github.com/datamade/councilmatic-starter-template right?

**Comment by reginafcompton** [comment]
I fleshed-out the documentation in the starter template, so this issue should be closed.
