### ISSUE TITLE
Add way for loaddata to filter when multiple sources

### ISSUE THREAD

**Issue by patcon** [datamade/django-councilmatic#46]
Objects in the toronto scrapers sometimes have multiple sources, since the data comes from several places. Would be great if loaddata could be configured with per-type filters (perhaps regex) that selected the main url pattern for the object, instead of just taking the first

**Comment by fgregg** [comment]
Is there a case when you wouldn't want all of the sources to be in the councilmatic instance? Could we just reconfigure to load them all?

**Comment by patcon** [comment]
We use a bunch of hidden endpoints that are not really intended for normal viewing. Since it was arcane knowledge to get the data out of the old system, seems to make sense to add it as a source. But yeah, def doesn't belong as a link on a user-friendly site :)

Things like:

* http://app.toronto.ca/tmmis/decisionBodyProfile.do?function=doGetMembers&decisionBodyId=1323&showLink=true
* http://app.toronto.ca/tmmis/meetingCalendarView.do?function=calendarCellView&year=2016&month=2&date=10

So I suppose either 1) we filter, or 2) take it out of the scraper and only have partial source.

**Comment by fgregg** [comment]
Not disagreeing about filtering, just wondering if it might best to filter
at application layer.

**Comment by patcon** [comment]
Ah, gotcha. So load all, and filter in application? I like that approach :)

**Comment by fgregg** [comment]
Yup.
