### ISSUE TITLE
better rich legislation snippet descriptions 

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic#55]
This is what it look like when you share a bill on facebook:

https://chicago.councilmatic.org/legislation/o-2016-697/

<img width="398" alt="screen shot 2016-03-20 at 8 16 26 pm" src="https://cloud.githubusercontent.com/assets/919583/13908805/c9e0bb36-eed8-11e5-9b0a-7d3019e2ea55.png">

Should show the title of the ordinance, and description of it, instead of the boilerplate councilmatic stuff

**Comment by fgregg** [comment]
This has been fixed
