### ISSUE TITLE
Use role label from database in templates

### ISSUE THREAD

**Issue by patcon** [datamade/django-councilmatic#61]
On a few templates, we're doing using "Member" and "Chairperson" as the label. Would it still cover our use-cases on chi and nyc if we took this from the row data and title-case it?

* https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templates/councilmatic_core/committee.html#L113
* https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templates/councilmatic_core/committee.html#L131
* https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templates/councilmatic_core/person.html#L152
* https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templates/councilmatic_core/person.html#L160

In particular, this would allow a city like Toronto, with "Chair" and "Vice Chair" positions to simply override the `Organization#chairs` method to include both those, while still using all the django-councilmatic templates as-is. This is most interesting for chairs right now, but down the road, Toronto will have committees with members who are private citizens or city staff or councillors, and it might be nice to have dynamic labels for members too.

But basically, just seems nice to pull from db than hardcode into template. Thoughts?

**Comment by patcon** [comment]
And in terms of having separate loops for both chair and members, am I correct in assuming that it would stay relevant, as the intention is to make sure chair roles are sorted to top?

**Comment by cathydeng** [comment]
Chicago & NYC both have the concept of chairperson & member, but the actual role names differ in the db (hence why we have the `COMMITTEE_CHAIR_TITLE` setting)

& yup, the two loops are to ensure that the chair shows up at the top, before non-chairs

in general, I don't think we should go down the rabbit hole of making all the django-councilmatic templates work for every city - imo it's only worth changing django-councilmatic templates if there's an improvement for multiple cities. for this particular case, I'd override the views/templates in toronto councilmatic & have them support the types of members that toronto committees have

**Comment by patcon** [comment]
fwiw, this doesn't strike me as consistent with what @fgregg was saying earlier:
https://github.com/datamade/django-councilmatic/pull/56#issuecomment-204715931

If you guys change your minds, I'm totally happy and eager to submit the PR for the US scrapers to get them using any label you'd like, and an SQL query that could be run to bring the current DB in line.

**Comment by cathydeng** [comment]
ok there are two slightly different issues here: consistency of data in the db, & how stuff renders in templates

I'm addressing the latter: aside from what the role is in the database, displaying 3 types of members is still going to be a different template than ordering 2 types of members, so the template should be overridden anyways

given that we (Datamade) have limited time to spend on supporting other councilmatic instances, I think we should prioritize our time on django-councilmatic issues that involve data loading & models, over those that involve views & templates (these are meant to be customized & overridden, hence the class based views). we should also be prioritizing bug fixes over enhancements
