### ISSUE TITLE
Some EventParticipants in NYC multiple-participant Events not listed

### ISSUE THREAD

**Issue by mccc** [datamade/django-councilmatic#68]
E.g. for this event: http://legistar.council.nyc.gov/MeetingDetail.aspx?ID=226773&GUID=FC8D05EC-496F-4F60-9420-24C634575781

There are three participants:

1. Committee on Aging
2. Committee on Mental Health, Developmental Disability, Alcoholism, Drug Abuse and Disability Services
3. Committee on General Welfare
 
But the NYC Councilmatic event: https://nyc.councilmatic.org/event/226773/

Only affiliates #1 and #3. This is sort of a parsing bug in the NYC scraper, but reflects a greater problem where the "Jointly" information is apparently hand-entered. For example:

http://legistar.council.nyc.gov/MeetingDetail.aspx?ID=311351&GUID=A9A5B39D-EFE4-47E8-B92C-3995AA32EC0C&Options=info&Search= 

Here, the Committee on Housing and Buildings is misspelled "Committee on Housing and Buldings", so that committee is not linked as an EventParticipant to the Event (https://nyc.councilmatic.org/event/311351/). But the inverse event (http://legistar.council.nyc.gov/MeetingDetail.aspx?ID=311352&GUID=F6610673-AC07-4752-8294-FA38280565A0&Options=&Search=) is linked correctly (https://nyc.councilmatic.org/event/311352/)

**Comment by fgregg** [comment]
If we want to fix this, we should fix it in the scraper. Could you open up
an issue there.
