### ISSUE TITLE
upcoming_committee_meetings() incorrectly displays Council meetings

### ISSUE THREAD

**Issue by trivisonno** [datamade/django-councilmatic#69]
In models.py, L649-650, the upcoming_committee_meetings function only excludes very specific objects that contain the text "City Council Stated Meeting".  This might be specific to a particular city, because my city's Council meeting events are being listed in the committee events section.

Similar to the next_city_council_meeting (L631) and most_recent_past_city_council_meeting (L639) functions, I changed L649-650 to only exclude CITY_COUNCIL_MEETING_NAME:     
```
def upcoming_committee_meetings(cls):
        return cls.objects.filter(start_time__gt=datetime.now())\
                  .exclude(name__icontains=settings.CITY_COUNCIL_MEETING_NAME)\
                  .order_by('start_time').all()[:3]
```

That change corrected the problem, but I'm not sure if it would break Chicago's or NYC's setup.

**Comment by cathydeng** [comment]
hi @trivisonno - nice catch, this wasn't supposed to be hard coded, thank you! this change should be fine for Chicago & NYC, since both have `CITY_COUNCIL_MEETING_NAME` set.

do you want to submit a pull request, or would you rather I make the change?

**Comment by trivisonno** [comment]
@cathydeng Probably be best for you to make the change, my git skills are still pretty poor unfortunately...
