### ISSUE TITLE
Add pol.is support to legislation pages

### ISSUE THREAD

**Issue by patcon** [datamade/django-councilmatic#76]
Should be very easy to do with the way their embeds work.

About pol.is:

https://medium.com/the-wtf-economy/creating-a-culture-of-continuous-feedback-1b97523ad11e#.a2hnvuow7

> pol.is is designed from the ground up to be a technology that can completely automate getting feedback from groups of people of any size, even tens of thousands. Humans ask questions that come naturally of large populations, and receive digestible results that they can use to ask further questions.

https://blog.pol.is/pol-is-in-taiwan-da7570d372b5#.7f5vs0r8x

cc: @colinmegill

**Comment by cathydeng** [comment]
I'm not convinced that something like this would get enough usage/traction for the benefits to outweigh the costs associated with incorporating a new service (sure it may be easy, but it comes at the cost of overall clarity/simplicity/maintainability). also, given that this is a startup, it could change or go away at any time.

imo experiments like this belong in a specific councilmatic instance, not in django-councilmatic, which is just for common core functionality.
