### ISSUE TITLE
UI & visual tweaks for notifications

### ISSUE THREAD

**Issue by cathydeng** [datamade/django-councilmatic#77]
- [x] consolidate all user stuff in navbar to a dropdown menu if user is logged in
- [x] 'log in/sign up' in nav bar -> 'login'
- [ ] only require one password for signup
- [x] signup/login pane alignment & padding
- [ ] change '[create subscription]' & '[remove subscription]' to icons w/ state, w/ text upon hover. should prob also be button b/c it is an action, to differentiate between rss link next to it
- [ ] improve ui for removing subscriptions - remove button + modal confirmation
- [x] on manage subscriptions page, move explanatory text from side well to top of page. need to add some indication of what the alerts will be (just email?) & how they are triggered
- [x] add some icons on subscriptions page
- [x] 'alerts' -> 'subscriptions'

**Comment by reginafcompton** [comment]
Done (with the exception of the "one password for signup"). All these updates are live for NYC.
