### ISSUE TITLE
notifications: bug when creating multiple alerts with same bill search term but different filters

### ISSUE THREAD

**Issue by cathydeng** [datamade/django-councilmatic#81]
need to dig into this

**Comment by reginafcompton** [comment]
Yes....this was fixed, but it seems a similar issue arose with subscribing to searches in general. The page indicts that I am not logged in, though I am: 

<img width="553" alt="screen shot 2017-02-23 at 11 13 54 am" src="https://cloud.githubusercontent.com/assets/13078679/23270389/4f50984a-f9b9-11e6-8d06-2ccfe31a96cd.png">

**Comment by reginafcompton** [comment]
Fixed this. Changes will go out in the next release of Django-Councilmatic.
