### ISSUE TITLE
Use named URLs in base.html

### ISSUE THREAD

**Issue by reginafcompton** [datamade/django-councilmatic#87]
**Line 36**

@evz 

Use the named URL in base.html, rather than hard-coding the path name. 

I suppose this could safely work.....

```
<a href='/{{ CITY_VOCAB.COUNCIL_MEMBER }}'>{{ CITY_VOCAB.COUNCIL_MEMBERS }}</a>
```

**Comment by evz** [comment]
closed with 8fdd2033a5d76dc42a8bc4d70984b2a565474e38
