### ISSUE TITLE
have PDFs open in a new tab, or embedded, instead of download

### ISSUE THREAD

**Issue by cathydeng** [datamade/django-councilmatic#9]

**Comment by cathydeng** [comment]
related to https://github.com/datamade/property-image-cache/issues/1

**Comment by fgregg** [comment]
Do we want do this for all pdfs, or just the bill pdfs?

On Tue, Dec 15, 2015 at 4:09 PM, Cathy Deng <notifications@github.com>
wrote:

> related to datamade/property-image-cache#1
> <https://github.com/datamade/property-image-cache/issues/1>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/django-councilmatic/issues/9#issuecomment-164910013>
> .
>



-- 
773.888.2718

**Comment by cathydeng** [comment]
embed bill pdfs using pdf.js, open attached pdfs in new tab
