### ISSUE TITLE
links in list of leg types on templates/partials/component_bill_type_table.html don't return results

### ISSUE THREAD

**Issue by hancush** [datamade/django-councilmatic#93]
[see line 13](https://github.com/datamade/django-councilmatic/blob/193f39c8e169e698bab1cb894287979652ca1cb8/councilmatic_core/templates/partials/component_bill_type_table.html#L13): `<a href="/search/?q=&selected_facets=bill_type_exact:{{leg_type.search_term}}">`

resulting url has search_term in title case, i.e. `/search/?q=&selected_facets=bill_type_exact:Mayor%27s%20Message`; search terms should be lowercase. either tack on `.lower` in template or wherever `search_term` comes from? (i don't see it [referenced anywhere else](https://github.com/datamade/django-councilmatic/search?utf8=%E2%9C%93&q=search_term), template fix may suffice?)

**Comment by reginafcompton** [comment]
Fixed....needed to update link itself.
Also, in settings_jurisdiciton.py, the "search_term" for LEGISLATION_TYPE_DESCRIPTIONS needs to be lowercase. Changes for this made in LA Metro. Will open new issue for Chicago and NYC.
