### ISSUE TITLE
new keyword search resets filters

### ISSUE THREAD

**Issue by derekeder** [datamade/django-councilmatic#98]
On the search page, any filters I have are reset when I enter a new keyword.

Steps to reproduce:
1. [Do a search](https://chicago.councilmatic.org/search/?q=police)
2. Select some filters
3. Change the keyword you are searching on
4. Filters are reset

These filters should be retained when new keywords are searched for.

**Comment by reginafcompton** [comment]
This is done and implemented on the LA Metro site. (Will add an issue for NYC.)
